### ISSUE TITLE
top_viral_desc for custom DB/taxless DB is NA. Should be more informative

### ISSUE THREAD

**Issue by thackl** [thackl/detectEVE#28]
For top_viral_desc, use top VDB description as fallback if no viral hits are available, e.g. if the custom DB has no taxonomy info.

**Comment by thackl** [comment]
@nbrait This should also be fixed now, but I didn't have a good example to test it. Could you verify that this now works and close this issue afterwards?

**Comment by nbrait** [comment]
works well.
